### ISSUE TITLE
Wildbow doesn't want ebook copies (and especially not scrapers) out there.

### ISSUE THREAD

**Issue by gbear605** [vanceza/worm-serial-downloader#1]
He's said that these copies and scrapers are the reason that at least one publisher hasn't contacted him.

**Comment by za3k** [comment]
Much appreciated for both the comment and the politeness. I will strongly consider making this private, especially if wildbow is at the stage of talking to publishers.

Link to some such comment please, esp. re scrapers? I don't like to act on secondhand complaints on principle.

I deliberately omitted a copy of the book to avoid people being able to pass a copy around, and planned to remove this scaper once there was an official version. I provided this a scraper rather than a copy to make it /harder/ to get a copy of the book, because I don't want thoughtless people to have a copy, but I can understand how the (incorrect) sentiment could arise that scrapers are worse.

You should also know (if you're not technically inclined) that this scraper represents about an hour's work for most programmers (when I told someone I wrote it they said "yes, I already wrote my own"), and so it's a very minor barrier of convenience in reality--anyone who can understand how to run a scraper can already scrape the site without this repository. (For example, using 'wget' which is the prepackaged program that downloads a website and is available on basically every linux machine in the world.) But whether this makes it hard to archive is almost irrelevant; I understand that publishers do not understand and care about the actual technical reality.

**Comment by gbear605** [comment]
Here's a reddit thread about it that WIldbow was involved with:
https://www.reddit.com/r/Parahumans/comments/2tn2kz/after_finding_this_subreddit_with_the_random/

"Putting work out there like I am is a fairly unestablished thing, and a
lot of companies, publishers, whatevers, are sort of paying attention and
watching and testing the water here and there by making deals with certain
parties (ie. Stephanie Meyer was a fanfic author, I know some serials have
received deals in the past). But it's still untested waters.
And that's without getting into all the other headaches of distribution and
attribution and simply keeping tabs on everything.
I'm not saying this is illegal. I'm saying that I've tried to be cool in
general as authors go, and there's enough headaches on my end when people
distribute scrapers or ebooks that, well, perpetuating that isn't cool as
the fan's end of things go. In some cases this sort of stuff has caused me
a fair bit of grief.
So I'm simply asking fans to reach out and say, "Hey, scraper dude, Wildbow
would rather you didn't have this up". If they say 'lol fuck you' or
something in that vein, then just let me know about it."

"When I say that this sort of thing causes me some grief and headaches, I'm
pointing to situations where an agent I've talked to now and again (one
that has worked with big six publishers in the past, and with authors who
you'd see in major book chains) is emailing me to say that someone had
expressed initial interest and they'd stopped because of one instance
they'd run into where stuff was being distributed, and maybe I should talk
to the fan in question. I did and the fan who was hosting the piece in
question very quickly and politely took it down."

**Comment by za3k** [comment]
The link you provided doesn't include that comment. Perhaps it's been removed?

In any case, I appreciate your letting me know, and I'll take this down unless wildbow's main website goes down with no official print version, in which case I'll try to contact wildbow before deciding what to do. In the future please do link to direct content when contacting programmers, rather than offering a secondhand message.

**Comment by gbear605** [comment]
Here are the permalinks to the reddit comments in that thread, fyi:

https://www.reddit.com/r/Parahumans/comments/2tn2kz/after_finding_this_subreddit_with_the_random/co0qb2f
https://www.reddit.com/r/Parahumans/comments/2tn2kz/after_finding_this_subreddit_with_the_random/co0oo5o

**Comment by za3k** [comment]
Whoops, my mistake. I did find those with some checking by hand--it looks like reddit's search is just lacking (I don't use the site so I wasn't familiar)
